# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  # 手动执行ci
  workflow_dispatch:
    inputs:
      tag:
        description: 'Test Tag'
        required: true
        default: 'test'
        type: choice
        options:
          - dev
          - test
          - uat
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  maven_build:

    runs-on: ubuntu-latest
    # 最后一个step（Update dependency graph）的权限不知道是啥，暂时给到全部的权限
    #permissions:
     # contents: read
      #packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

#    - name: Log in to the github Container registry
#      uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#      with:
#        registry: ${{ env.REGISTRY }}
#        username: ${{ github.actor }}
#        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Docker Login Huawei SWR
      uses: docker/login-action@v2.0.0
      with:
        # Server address of Docker registry. If not set then will default to Docker Hub
        registry: ${{ secrets.SWR_URL }}
        # Username used to log against the Docker registry
        username: ${{ secrets.SWR_USER }}
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.SWR_PASSWORD }}
        # Log out from the Docker registry at the end of a job
        logout: false
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
      with:
        images: ${{ secrets.SWR_URL }}/${{ env.IMAGE_NAME }}
        tags: |
          type=sha,enable=true,priority=100,prefix={{branch}}-,suffix=,format=short
    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
